export const cars = [
  {
    id: 1,
    label: "audi",
    value: "audi",
  },
  {
    id: 2,
    label: "bmw",
    value: "bmw",
    logo: "/carlogo/bmw-logo.svg",
    alt: "bmw",
  },
  {
    id: 3,
    label: "buick",
    value: "buick",
    logo: "/carlogo/buick-logo.svg",
    alt: "buick",
  },
  {
    id: 4,
    label: "changan",
    value: "changan",
    logo: "/carlogo/changan-logo.svg",
    alt: "",
  },
  {
    id: 5,
    label: "cherry",
    value: "cherry",
    logo: "/carlogo/cherry-logo.svg",
    alt: "",
  },
  {
    id: 6,
    label: "chevrolet",
    value: "chevrolet",
    logo: "/carlogo/chevrolet-logo.svg",
    alt: "",
  },
  {
    id: 7,
    label: "chrysler",
    value: "chrysler",
    logo: "/carlogo/chrysler-logo.svg",
    alt: "",
  },
  {
    id: 8,
    label: "citroen",
    value: "citroen",
    logo: "/carlogo/citroen-logo.svg",
    alt: "",
  },
  {
    id: 9,
    label: "daewoo",
    value: "daewoo",
    logo: "/carlogo/daewoo-logo.svg",
    alt: "",
  },
  {
    id: 10,
    label: "daihatsu",
    value: "daihatsu",
    logo: "/carlogo/daihatsu-logo.svg",
    alt: "",
  },
  {
    id: 11,
    label: "dodge",
    value: "dodge",
    logo: "/carlogo/dodge-logo.svg",
    alt: "",
  },
  {
    id: 12,
    label: "faw",
    value: "faw",
    logo: "/carlogo/faw-logo.svg",
    alt: "",
  },
  {
    id: 13,
    label: "ferrari",
    value: "ferrari",
    logo: "/carlogo/ferrari-logo.svg",
    alt: "",
  },
  {
    id: 14,
    label: "fiat",
    value: "fiat",
    logo: "/carlogo/fiat-logo.svg",
    alt: "",
  },
  {
    id: 15,
    label: "ford",
    value: "ford",
    logo: "/carlogo/ford-logo.svg",
    alt: "",
  },
  {
    id: 16,
    label: "GAC",
    value: "GAC",
    logo: "/carlogo/GAC-logo.svg",
    alt: "",
  },
  {
    id: 17,
    label: "geely",
    value: "geely",
    logo: "/carlogo/geely-logo.svg",
    alt: "",
  },
  {
    id: 18,
    label: "gmc",
    value: "gmc",
    logo: "/carlogo/gmc-logo.svg",
    alt: "",
  },
  {
    id: 19,
    label: "greatwall",
    value: "greatwall",
    logo: "/carlogo/greatwall-logo.svg",
    alt: "",
  },
  {
    id: 20,
    label: "haval",
    value: "haval",
    logo: "/carlogo/haval-logo.svg",
    alt: "",
  },
  {
    id: 21,
    label: "honda",
    value: "honda",
    logo: "/carlogo/honda-logo.svg",
    alt: "",
  },
  {
    id: 22,
    label: "hummer",
    value: "hummer",
    logo: "/carlogo/hummer-icon.svg",
    alt: "",
  },
  {
    id: 23,
    label: "hyundai",
    value: "hyundai",
    logo: "/carlogo/hyundai-icon.svg",
    alt: "",
  },
  {
    id: 24,
    label: "infinity",
    value: "infinity",
    logo: "/carlogo/infinity-icon.svg",
    alt: "",
  },
  {
    id: 25,
    label: "jeep",
    value: "jeep",
    logo: "/carlogo/jeep-icon.svg",
    alt: "",
  },
  {
    id: 26,
    label: "kia",
    value: "kia",
    logo: "/carlogo/kia-logo.svg",
    alt: "",
  },
  {
    id: 27,
    label: "land",
    value: "land",
    logo: "/carlogo/land-logo.svg",
    alt: "",
  },
  {
    id: 28,
    label: "mazda",
    value: "mazda",
    logo: "/carlogo/mazda-logo.svg",
    alt: "",
  },
  {
    id: 29,
    label: "mercedes",
    value: "mercedes",
    logo: "/carlogo/mercedes-logo.svg",
    alt: "",
  },
  {
    id: 30,
    label: "mitsubishi",
    value: "mitsubishi",
    logo: "/carlogo/mitsubishi-logo.svg",
    alt: "",
  },
  {
    id: 31,
    label: "nissan",
    value: "nissan",
    logo: "/carlogo/nissan-logo.svg",
    alt: "",
  },
  {
    id: 32,
    label: "porsche",
    value: "porsche",
    logo: "/carlogo/porsche-logo.svg",
    alt: "",
  },
  {
    id: 33,
    label: "suzuki",
    value: "suzuki",
    logo: "/carlogo/suzuki-logo.svg",
    alt: "",
  },
  {
    id: 34,
    label: "toyota",
    value: "toyota",
    logo: "/carlogo/toyota-logo.svg",
    alt: "",
  },
  {
    id: 35,
    label: "volkswagen",
    value: "volkswagen",
    logo: "/carlogo/volkswagen-logo.svg",
    alt: "",
  },
  {
    id: 36,
    label: "astonmartin",
    value: "astonmartin",
    logo: "/carlogo/astonmartin-logo.svg",
    alt: "",
  },
  {
    id: 40,
    label: "cadillac",
    value: "cadillac",
    logo: "/carlogo/cadillac-logo-alt.svg",
    alt: "",
  },
];

export const carsModel = [
  {
    id: 1,
    carFactoryId: 1,
    label: "audi car",
    value: "audi",
  },
  {
    id: 2,
    carFactoryId: 1,
    label: "bmw audi car",
    value: "bmw",
  },
  {
    id: 3,
    carFactoryId: 2,
    label: "buick bmw car",
    value: "buick",
  },
  {
    id: 4,
    carFactoryId: 2,
    label: "changan  bmw car",
    value: "changan",
  },
  {
    id: 5,
    carFactoryId: 2,
    label: "cherry  bmw car",
    value: "cherry",
  },
  {
    id: 6,
    carFactoryId: 5,
    label: "chevrolet",
    value: "chevrolet",
  },
  {
    id: 7,
    carFactoryId: 3,
    label: "chrysler",
    value: "chrysler",
  },
  {
    id: 8,
    carFactoryId: 3,
    label: "citroen",
    value: "citroen",
  },
  {
    id: 9,
    carFactoryId: 3,
    label: "daewoo",
    value: "daewoo",
  },
  {
    id: 10,
    carFactoryId: 4,
    label: "daihatsu",
    value: "daihatsu",
  },
  {
    id: 11,
    carFactoryId: 4,
    label: "dodge",
    value: "dodge",
  },
  {
    id: 12,
    carFactoryId: 1,
    label: "faw audi car",
    value: "faw",
  },
  {
    id: 13,
    carFactoryId: 4,
    label: "ferrari",
    value: "ferrari",
  },
  {
    id: 14,
    carFactoryId: 1,
    label: "fiat audi car",
    value: "fiat",
  },
  {
    id: 15,
    carFactoryId: 1,
    label: "ford audi car",
    value: "ford",
  },
  {
    id: 16,
    carFactoryId: 1,
    label: "GAC audi car",
    value: "GAC",
  },
  {
    id: 17,
    carFactoryId: 1,
    label: "geely audi car",
    value: "geely",
  },
  {
    id: 18,
    carFactoryId: 1,
    label: "gmc audi car",
    value: "gmc",
  },
  {
    id: 19,
    carFactoryId: 1,
    label: "greatwall audi car",
    value: "greatwall",
  },
  {
    id: 20,
    carFactoryId: 1,
    label: "haval audi car",
    value: "haval",
  },
  {
    id: 21,
    carFactoryId: 1,
    label: "honda audi car",
    value: "honda",
  },
  {
    id: 22,
    carFactoryId: 1,
    label: "hummer audi car",
    value: "hummer",
  },
  {
    id: 23,
    carFactoryId: 1,
    label: "hyundai audi car",
    value: "hyundai",
  },
  {
    id: 24,
    carFactoryId: 1,
    label: "infinity audi car",
    value: "infinity",
  },
  {
    id: 25,
    carFactoryId: 1,
    label: "jeep audi car",
    value: "jeep",
  },
  {
    id: 26,
    carFactoryId: 1,
    label: "kia audi car",
    value: "kia",
  },
  {
    id: 27,
    carFactoryId: 1,
    label: "land audi car",
    value: "land",
  },
  {
    id: 28,
    carFactoryId: 1,
    label: "mazda audi car",
    value: "mazda",
  },
  {
    id: 29,
    carFactoryId: 1,
    label: "mercedes audi car",
    value: "mercedes",
  },
  {
    id: 30,
    carFactoryId: 1,
    label: "mitsubishi audi car",
    value: "mitsubishi",
  },
  {
    id: 31,
    carFactoryId: 1,
    label: "nissan audi car",
    value: "nissan",
  },
  {
    id: 32,
    carFactoryId: 1,
    label: "porsche audi car",
    value: "porsche",
  },
  {
    id: 33,
    carFactoryId: 1,
    label: "suzuki audi car",
    value: "suzuki",
  },
  {
    id: 34,
    carFactoryId: 1,
    label: "toyota audi car",
    value: "toyota",
  },
  {
    id: 35,
    carFactoryId: 1,
    label: "volkswagen audi car",
    value: "volkswagen",
  },
  {
    id: 36,
    carFactoryId: 1,
    label: "astonmartin audi car",
    value: "astonmartin",
  },
  {
    id: 40,
    carFactoryId: 1,
    label: "cadillac audi car",
    value: "cadillac",
  },
];
